name: Package Mac App

on:
  push:
    branches: [release]

jobs:
  package-macos-application:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn global add bozon
      - run: echo "⚙️ Building MacOS application"
